### ISSUE TITLE
TypeError: can't concat str to bytes (python 3)

### ISSUE THREAD

**Issue by lestephane** [blackknight36/ssh-static-key-generator#1]
Any clue how to make it work in a python 3 context?
```python
$ python mk_ed25519_key.py 
Traceback (most recent call last):
  File "mk_ed25519_key.py", line 95, in <module>
    keydata =  putEd25519Key(sk, c)
  File "mk_ed25519_key.py", line 77, in putEd25519Key
    privkey_block += chr(n & 0xFF)
TypeError: can't concat str to bytes
```

**Comment by blackknight36** [comment]
Most likely the issue is that chr(n & 0xFF) is returning a string value which needs to be converted to binary in order to be added to the privkey_block data.  I haven't tested this script on python3 but I can look into it when I have some time.
